---
deployment:
  tasks:
    - export DEPLOYPATH=/home/torringt/public_html/
    - source /home/torringt/nodevenv/repositories/site/20/bin/activate && cd /home/torringt/repositories/site && npm install
    - source /home/torringt/nodevenv/repositories/site/20/bin/activate && cd /home/torringt/repositories/site && npm run build
    - /bin/cp -R dist/. $DEPLOYPATH
